#version: '3.9'

services:
  db:
    image: postgres:15
    container_name: bcf-postgres
    environment:
      POSTGRES_USER: bcfuser
      POSTGRES_PASSWORD: bcfpass
      POSTGRES_DB: bcfdb
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bcf-api
    ports:
      #- "5000:5000"
      - "80:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
